/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const BreathingVideosLazyRouteImport = createFileRoute('/breathing-videos')()
const IndexLazyRouteImport = createFileRoute('/')()

const BreathingVideosLazyRoute = BreathingVideosLazyRouteImport.update({
  id: '/breathing-videos',
  path: '/breathing-videos',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/breathing-videos.lazy').then((d) => d.Route),
)
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/breathing-videos': typeof BreathingVideosLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/breathing-videos': typeof BreathingVideosLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/breathing-videos': typeof BreathingVideosLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/breathing-videos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/breathing-videos'
  id: '__root__' | '/' | '/breathing-videos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  BreathingVideosLazyRoute: typeof BreathingVideosLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/breathing-videos': {
      id: '/breathing-videos'
      path: '/breathing-videos'
      fullPath: '/breathing-videos'
      preLoaderRoute: typeof BreathingVideosLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  BreathingVideosLazyRoute: BreathingVideosLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
